# Generated by Django 3.0.3 on 2020-05-12 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20200511_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='fees_in_world',
            new_name='fess_in_world',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='world_premier',
            new_name='world_premiere',
        ),
    ]
